export const FETCH_PLAYER_SUCCESS = "FETCH_PLAYER_SUCCESS"
export const FETCH_PLAYER_ERROR = "FETCH_PLAYER_ERROR"
export const FETCH_FIND_PLAYER_SUCCESS = "FETCH_FIND_PLAYER_SUCCESS"

export const FETCH_FILMS_SUCCESS = "FETCH_FILMS_SUCCESS"
export const FETCH_FILMS_ERROR = "FETCH_FILMS_ERROR"
export const FETCH_FIND_FILMS_SUCCESS = "FETCH_FIND_FILMS_SUCCESS"

export const WIDE_SEARCH = "WIDE_SEARCH"
export const RESET_WIDE_SEARCH = "RESET_WIDE_SEARCH"